### ISSUE TITLE
Unable to load markets

### ISSUE THREAD

**Issue by kimonooxidado** [bocabitlabs/buho-stocks#62] opened 2023-04-16 11:53 UTC
Hello and good morning:

When I try to initialize markets I get the following error: 

Unable to load markets
Request failed with status code 500

I have been able to initialize benchmarks, currencies and sectors, but I can't do the same with markets.

Please note that I have followed the steps described in the documentation to create the initial administrator user:

python manage.py createsuperuser

As well as the steps described in release v0.100.2:

python manage.py migrate

find . -path '*/migrations/*.py' -not -name '__init__.py' -delete
python manage.py makemigrations
python manage.py migrate

python manage.py set_dividends_total
python manage.py set_shares_total
python manage.py set_rights_total

The version I currently use is v0.100.4 on docker with sqlite. Although this error also happened to me with version v0.100.2.

Thanks in advance for the help.

**Comment by renefs** [comment] 2023-04-16 15:45
Hi,

That error should be logging something on the application logs. Can you share the container logs to know the source of the issue? Also, since version `0.100.0` there is no need to create a super user since all the operations can be done from the application itself.

Cheers.

**Comment by renefs** [comment] 2023-04-16 16:14
Another thing that came to my mind is that maybe you haven't added the following settings to your `config.py` (mandatory since version `0.100.0`.

```python
CORS_ALLOWED_ORIGINS = [
    "http://your-application.your-host.com",
    "http://127.0.0.1:3000",
]
```

Sorry but I forgot to add it to the migration steps.

**Comment by kimonooxidado** [comment] 2023-04-16 16:35
Thank you very much for your help.

The truth is that I had already added, in config.py, the above mentioned configuration. And yet, the error still occurs.

I am going to share the container logs, as well as the config.py file. 
[buho-stocks-app_logs.txt](https://github.com/bocabitlabs/buho-stocks/files/11242841/buho-stocks-app_logs.txt)
[config.txt](https://github.com/bocabitlabs/buho-stocks/files/11242844/config.txt)

**Comment by renefs** [comment] 2023-04-16 19:24
I don't see any issue on the logs other than the 500 errors... I can think on two possible solutions to go further on the debugging:
1. Set `DEBUG = True` on the `config.py` and restart the application. Then, on the browser, open the developer tools and check the requests on the `Network` tab. There you can check the response, that should include more information of the error.
2. Set `DEBUG = True` on the `config.py` and restart the application.  Then go to `/swagger/`, find the `GET /markets/` endpoint and click on **Try it out**. On the response you should see the error that you can share.
 
I tried myself starting from scratch with SQLite, but unfortunately, I didn't manage to reproduce the error.

**Comment by kimonooxidado** [comment] 2023-04-17 06:50
Perfect, @renefs 

According to the steps described, above, in point number two. I am going to attach the records I get. 

Comment that the IP address and port data have been modified for security reasons. So if they compare with those previously sent (container logs and config.py) it is possible that these data do not match.

Thank you very much in advance for the collaboration.

[response_1681713073735.txt](https://github.com/bocabitlabs/buho-stocks/files/11247104/response_1681713073735.txt)

**Comment by renefs** [comment] 2023-04-17 07:20
Hi, It seems that for some reason you are missing the `timezone` column in the `markets` table.

 I would try the following to see if it fixes the problem:

You can try to run the migrations again:

```bash
python manage.py migrate
```

Or, you can add the column manually to your table (I haven't tested myself te following command, but it should work):

```sql
ALTER TABLE markets_market
ADD "timezone" varchar(200) NOT NULL;
```

If you are not familiar with SQL, you can use an application like TablesPlus (on Mac) to modify the database.

I hope this works for you.

**Comment by kimonooxidado** [comment] 2023-04-17 12:36
Ok, perfect. I will try that option. 

Or failing that, if it happens again, I will try with mySQL or postgreSQL.

Thank you very much for your help.

**Comment by renefs** [comment] 2023-05-03 07:19
@kimonooxidado did it work for you?

**Comment by renefs** [comment] 2023-05-06 06:43
I'm closing this ticket since the problem should be solved after last version changes and changes in #70

**Closed by renefs** 2023-05-06 06:43 UTC
Labels: bug
